services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    links:
      - influxdb:influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - ${INFLUXDB_PORT}:8086
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - influxdb-storage:/var/lib/influxdb

volumes:
  influxdb-storage:
  grafana-storage: